source 'https://rubygems.org'
gem 'therubyracer'
gem 'execjs' #execjs requires a js runtime and therubyracer installs a v8 javascript runtime
gem 'uglifier'
gem 's3_website'
gem 'jekyll', '~> 3.0.1'
gem 'jekyll-assets'
gem 'handlebars_assets'
gem 'sass', '~> 3.4.19'
gem 'sprockets' #, '~> 3.4.0'
